### ISSUE TITLE
Each user should have zero or one note related to each activity/travel

### ISSUE THREAD

**Issue by niuniuanran** [tantigers/TripTime#41]
**Describe the bug**
The current JSON data structure and TravelCard do not enforce that each user has one slot of note that they can update.

**To Reproduce**
1. Go to `src/spa/app/dummy-data/activity.js` and `src/spa/app/dummy-data/travel-between.js`. 2. See that `notes` are stored independent of people

**Expected behavior**
The JSON object should store note under each person.
The TravelCard component should render notes based on the updated data structure

**Comment by rafiazman** [comment]
Closing as this is not a bug
